apiVersion: v1
kind: Service
metadata:
  name: ml-gateway-service
spec:
  selector:
    app: ml-gateway-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP