apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2026-01-20T02:11:32Z"
  generation: 1
  labels:
    app: nginx-depl
  name: nginx-depl
  namespace: default
  resourceVersion: "481"
  uid: fd6ac5a9-d92c-4dbf-90a1-84a8e1f9ef03
spec:
  containers: 
  - image: nginx:1.16
    imagePullPolicy: Always
    name: nginx-dev
    resources: {}
    terminationMessagePath: /dev/termination-log
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
