apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-stg
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  skuName: StandardSSD_LRS