apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-prod
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  skuName: Premium_LRS