apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-stg
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4