apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-prod
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: pd-ssd
  fstype: ext4